### ISSUE TITLE
Release Packetry 0.1.0

### ISSUE THREAD

**Issue by martinling** [greatscottgadgets/packetry#116]
This is the tracking issue for the Packetry 0.1.0 release.

```[tasklist]
### Tasks not yet associated with an Issue or Pull Request
```

```[tasklist]
### Documentation
- [ ] https://github.com/greatscottgadgets/packetry/issues/123
```

```[tasklist]
### Issues
- [ ] https://github.com/greatscottgadgets/packetry/issues/120
```

```[tasklist]
### Review, merge or close outstanding pull requests
- [ ] https://github.com/greatscottgadgets/packetry/pull/115
```
